<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
    <SignAssembly>False</SignAssembly>
    <Company>969 Studios</Company>
    <PackageProjectUrl>https://ninesixnine.net</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="_REF\**" />
    <EmbeddedResource Remove="_REF\**" />
    <None Remove="_REF\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Icons\folder01.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".github\copilot-instructions.md" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Icons\folder01.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>